### ISSUE TITLE
Loading Microsoft Account

### ISSUE THREAD

**Issue by VinnyRoman** [ChristopherHX/mcpelauncher-manifest#81] opened 2020-05-02 12:12 UTC
Ive gone through the whole process and have downloaded the newest version on here of minecraft bedrock onto my mac but when I get into the game I am not able to sign into my Microsoft account it either goes and "we tried signing you into your microsoft account, but something went wrong." or it continusly loads.

**Comment by ChristopherHX** [comment] 2020-05-17 14:07
Duplicate of #42

**Closed by ChristopherHX** 2020-05-17 14:07 UTC
Labels: duplicate
