### ISSUE TITLE
Microsoft Account Wont Load

### ISSUE THREAD

**Issue by luciagcm** [ChristopherHX/mcpelauncher-manifest#62] opened 2020-03-25 16:29 UTC
Every time i log in to my microsoft account it just keeps loading forever or tells me it failed to log me in

**Comment by ChristopherHX** [comment] 2020-03-25 19:15
Please provide the game log, and follow the linked issue (make shure msa-daemon is running during login)
Duplicate of https://github.com/ChristopherHX/mcpelauncher-manifest/issues/42

**Closed by ChristopherHX** 2020-03-25 19:15 UTC
Labels: duplicate

**Comment by luciagcm** [comment] 2020-03-27 15:32
where do i find the game log

**Comment by luciagcm** [comment] 2020-03-27 15:33
also theres no linked issue

**Comment by luciagcm** [comment] 2020-03-27 15:43
HI im sorry i dont code or anything idk how to do these things could you give me a step by step or video? im on a mac

**Comment by ChristopherHX** [comment] 2020-03-27 22:36
BTW
- You need an xboxlive profile.
- Luck
- In the launcher upper right gear icon you will find a checkbox to show the log
- Try running `/Application/Minecraft\ Bedrock\ Launcher.app/Contents/MacOS/msa-daemon` in a Terminal, then try login (Do not close the Terminal before closing Minecraft)
- idk if the path is correct, might contains errors

**Comment by luciagcm** [comment] 2020-03-28 01:48
Okay thank you! Ill try that

**Comment by DavidUnknown** [comment] 2020-04-11 23:05
Hey! Hi
Could you please help me with the same but manjaro?
Xbox login not working
How i do to install msa daemon and activate it?
