### ISSUE TITLE
Using Realms can break the realm on other devices.

### ISSUE THREAD

**Issue by GameParrot** [ChristopherHX/mcpelauncher-manifest#275] opened 2021-06-16 13:14 UTC
i do not know if this is a bug in this launcher or if it is a bug in Minecraft itself. Sometimes when you are in a Realm, it freezes, then the screen turns blue, and it crashes. If you rejoin, it gets stuck on the Let's go screen and crashes. It also gets all messed up when attempting to join from my iPad after this happens.

**Comment by ChristopherHX** [comment] 2021-06-16 14:48
Duplicate of
https://github.com/minecraft-linux/mcpelauncher-manifest/issues/512

Your world is corrupted.

**Closed by ChristopherHX** 2021-06-16 14:48 UTC

**Comment by GameParrot** [comment] 2021-06-16 17:07
This is a Realm, not a world. I can't join from my iPad either. Other accounts can join, though. I am okay with losing the contents of my inventory.

**Comment by GameParrot** [comment] 2021-06-16 17:15
The issue I am experiencing is more like [MCPE-125201](https://bugs.mojang.com/browse/MCPE-125201)
