### ISSUE TITLE
Randomly crashing

### ISSUE THREAD

**Issue by Aaronlei17** [ChristopherHX/mcpelauncher-manifest#108] opened 2020-06-23 01:13 UTC
I downloaded _Minecraft_Bedrock_Launcher_0.0.132_macOS_10.12.0.dmg_ a few days ago and it randomly crash, But if didn't do anything it won't crash at all. I'm currently on macOS Catalina 10.15.5, and also when 10.15 stable version will come out for Catalina 10.15.5? So I won't crash anytime

**Comment by ChristopherHX** [comment] 2020-06-23 11:00
I know, but have no Solution.
You can switch your OS to GNU/Linux and get far more stable experience.
Please don't think the stable launcher won't crash at all, it's backend is just years older and better tested.
ng is very new and adds 64bit (the old backend cannot be used for 64bit)

**Comment by Aaronlei17** [comment] 2020-06-23 23:12
Christopher, so then will 10.15 stable will ever come out or it will never be added?

**Comment by Aaronlei17** [comment] 2020-06-23 23:12
> I know, but have no Solution.
> You can switch your OS to GNU/Linux and get far more stable experience.
> Please don't think the stable launcher won't crash at all, it's backend is just years older and better tested.
> ng is very new and adds 64bit (the old backend cannot be used for 64bit)

Christopher, so then will 10.15 stable will ever come out or it will never be added?

**Comment by ChristopherHX** [comment] 2020-07-08 14:23
> Christopher, so then will 10.15 stable will ever come out or it will never be added?

No, it cannot be added to stable (stable is a completly different program)
Especially apple will deprecate x86_64 in some years, arm64 isn't loading at all.

**Comment by Aaronlei17** [comment] 2020-08-19 17:27
> > Christopher, so then will 10.15 stable will ever come out or it will never be added?
> 
> No, it cannot be added to stable (stable is a completly different program)
> Especially apple will deprecate x86_64 in some years, arm64 isn't loading at all.

alright
ty

**Comment by ChristopherHX** [comment] 2021-03-10 13:53
duplicate of https://github.com/ChristopherHX/mcpelauncher-manifest/issues/97

**Closed by ChristopherHX** 2021-03-10 13:53 UTC
Labels: MacOs Catalina, RandomCrash, bug, help wanted, macOS
