### ISSUE TITLE
Unable to sign in on 1.13 or 1.14

### ISSUE THREAD

**Issue by docenig** [ChristopherHX/mcpelauncher-manifest#9] opened 2019-11-09 00:17 UTC
Running from Manjaro 18.1.2 with Xfce 4.14, both 1.13.0.34 and the latest 1.14 beta versions will launch and run successfully, but neither will sign in to a Microsoft account. Enabling the game log shows this line appears when the Sign In button is clicked:
```
18:01:24 Debug [XSAPI.Android] sign_in_impl: will NOT be showing UI
```
This appears both when the game is launched via the terminal string and after moving mcpelauncher-client to /usr/local/bin/ to run from the UI launcher. This is with both the older AUR versions of msa-daemon and msa-ui-qt and the latest versions from git.

**Comment by ChristopherHX** [comment] 2019-11-09 11:30
This is a duplicate of #5, my focus was getting it to run
but xbox live isn't as easy to implement as you may think
I neither know how mrarm got it to work on his original

**Comment by ChristopherHX** [comment] 2019-11-14 22:39
Should be fixed now

**Closed** 2019-11-16 19:51 UTC
