### ISSUE TITLE
Launcher Crashed

### ISSUE THREAD

**Issue by bigman239** [ChristopherHX/mcpelauncher-manifest#184] opened 2020-12-28 17:28 UTC
Did older Launcher Versions work on this PC?
```
12:28:09 Trace [HybrisUtils] Loaded OS library libz.dylib
12:28:09 Trace [HybrisUtils] Loaded OS library libm.dylib
12:28:10 Trace [HybrisUtils] Loaded OS library /private/var/folders/h3/55093wpd5392yvsyc3r_kjvw0000gn/T/AppTranslocation/235B1A32-E4DC-4FF4-99A3-81013E3C7198/d/Minecraft Bedrock.app/Contents/Resources/mcpelauncher/lib/native/x86_64/libfmod.dylib
Signal 11 received
Backtrace elements: 8
#0 0   mcpelauncher-client                 0x0000000107784f92 _ZN12CrashHandler12handleSignalEiPv + 226
#1 1   libsystem_platform.dylib            0x00007fff62226b5d _sigtramp + 29
#2 2   ???                                 0x0000000000000000 0x0 + 0
#3 3   mcpelauncher-client                 0x0000000107764bcd _ZN11HookManager7LibInfoC1EPv + 29
#4 4   mcpelauncher-client                 0x000000010776526a _ZN11HookManager10addLibraryEPv + 90
#5 5   mcpelauncher-client                 0x000000010745f633 main + 7571
#6 6   libdyld.dylib                       0x00007fff6203b3d5 start + 1
#7 7   ???                                 0x0000000000000007 0x0 + 7
Dumping stack...

Process exited with unexpected exit code: 6

```
# Disclaimer
If you don't answer these questions your issue will be closed

**Comment by ChristopherHX** [comment] 2020-12-28 22:10
Is there a youtube video to install the launcher the wrong way?
Is there an outdated blog post?

You opend the 9th duplicate of an error with an very outdated version of the launcher.
[See the list of all duplicates already exist](
https://github.com/ChristopherHX/mcpelauncher-manifest/issues?q=is%3Aissue+label%3AMissingUpdates+)

I have written a lot of answers, but it keeps coming up. v0.1b2 is current, but v0.1b1 found here: 
https://github.com/ChristopherHX/mcpelauncher-manifest/issues/154#issuecomment-731762708, is still never than the one you still have.

**Comment by ChristopherHX** [comment] 2020-12-28 22:22
Why you open this a second time, won't take your time to respond at all. Instead open a new issue with the same content????

You leave a bad impression after all, your last issue is
https://github.com/ChristopherHX/mcpelauncher-manifest/issues/176

**Closed by ChristopherHX** 2020-12-28 22:22 UTC
Labels: MissingUpdates, duplicate

**Comment by ChristopherHX** [comment] 2021-01-24 16:05
I heard of a potenially tampered Launcher from mediafire

You find offical releases from me on github (https://github.com/ChristopherHX/osx-packaging-scripts/releases/tag/ng.dmg).
They are still unsigned, but it seems to be reasonable to increase secureity.
