### ISSUE TITLE
beta 1.16.0.57 Minecraft exit non-zero code 11

### ISSUE THREAD

**Issue by PacketCat** [ChristopherHX/mcpelauncher-manifest#73] opened 2020-04-17 19:33 UTC
22:32:19 Info  [Launcher] Version: client 7c17ac3 / manifest 45f9d98
22:32:19 Info  [Launcher] CPU: GenuineIntel Intel(R) Core(TM)2 Duo CPU     T5270  @ 1.40GHz
22:32:19 Info  [Launcher] CPU supports SSSE3: YES
22:32:19 Trace [Launcher] Loading hybris libraries
22:32:19 Trace [HybrisUtils] Loaded OS library /usr/share/mcpelauncher/libs/native/libfmod.so.9.16
22:32:19 Trace [HybrisUtils] Loaded OS library libm.so.6
22:32:19 Trace [HybrisUtils] Loaded OS library libz.so.1
22:32:19 Info  [Launcher] Creating window
22:32:19 Trace [Launcher] Loading gamepad mappings: /usr/share/mcpelauncher/gamecontrollerdb.txt
22:32:19 Trace [Launcher] Loading gamepad mappings: /usr/share/mcpelauncher/gamecontrollerdb.txt
_eglutReadPNG: fopen failed
22:32:19 Trace [Launcher] Loading Minecraft library
linkerterminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to load Minecraft: Cannot load library: reloc_library[1378]:     0 cannot locate '_ZN4FMOD6System11setUserDataEPv'...

Process exited with unexpected exit code: 11

**Comment by ChristopherHX** [comment] 2020-04-17 20:59
Duplicate of https://github.com/ChristopherHX/mcpelauncher-manifest/issues/71#issuecomment-614890161

**Comment by PacketCat** [comment] 2020-04-18 15:34
Log when trying launch it from terminal:
```
mcpelauncher-client -dg ~/.local/share/mcpelauncher/versions/1.16.0.57 -dd ~/minecraftbe/beta
18:33:11 Info  [Launcher] Version: client 7c17ac3 / manifest 45f9d98
18:33:11 Info  [Launcher] CPU: GenuineIntel Intel(R) Core(TM)2 Duo CPU     T5270  @ 1.40GHz
18:33:11 Info  [Launcher] CPU supports SSSE3: YES
18:33:11 Trace [Launcher] Loading hybris libraries
18:33:12 Trace [HybrisUtils] Loaded OS library /usr/share/mcpelauncher/libs/native/libfmod.so.9.16
18:33:12 Trace [HybrisUtils] Loaded OS library libm.so.6
18:33:12 Trace [HybrisUtils] Loaded OS library libz.so.1
18:33:12 Info  [Launcher] Creating window
18:33:12 Trace [Launcher] Loading gamepad mappings: /usr/share/mcpelauncher/gamecontrollerdb.txt
18:33:12 Trace [Launcher] Loading gamepad mappings: /usr/share/mcpelauncher/gamecontrollerdb.txt
_eglutReadPNG: fopen failed
18:33:16 Trace [Launcher] Loading Minecraft library
linker/root/project/source/mcpelauncher/libhybris/src/jb/linker.c:2046| ERROR: failed to link libminecraftpe.so
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to load Minecraft: Cannot load library: reloc_library[1378]:     0 cannot locate '_ZN4FMOD6System11setUserDataEPv'...

Signal 6 received
Backtrace elements: 13
#0 mcpelauncher-client(_ZN12CrashHandler12handleSignalEiPv+0xc9) [0x568414cf]
#1 linux-gate.so.1(__kernel_sigreturn+0) [0xf7fb0b60]
#2 linux-gate.so.1(__kernel_vsyscall+0x9) [0xf7fb0b49]
#3 /lib/i386-linux-gnu/libc.so.6(gsignal+0xc6) [0xf78a3616]
#4 /lib/i386-linux-gnu/libc.so.6(abort+0x130) [0xf788b3f7]
#5 /usr/lib/i386-linux-gnu/libstdc++.so.6(+0x7d7f6) [0xf7c217f6]
#6 /usr/lib/i386-linux-gnu/libstdc++.so.6(+0x8be48) [0xf7c2fe48]
#7 /usr/lib/i386-linux-gnu/libstdc++.so.6(+0x8bec1) [0xf7c2fec1]
#8 /usr/lib/i386-linux-gnu/libstdc++.so.6(__cxa_rethrow+0) [0xf7c301f0]
#9 mcpelauncher-client(_ZN14MinecraftUtils16loadMinecraftLibERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x187) [0x56842a3d]
#10 mcpelauncher-client(main+0x1837) [0x567b43cc]
#11 /lib/i386-linux-gnu/libc.so.6(__libc_start_main+0xf9) [0xf788cfb9]
#12 mcpelauncher-client(_start+0x35) [0x567b11a5]
Dumping stack...
```

**Closed** 2020-04-18 15:46 UTC
Labels: duplicate
