### ISSUE TITLE
1.4.6.05 still not working after latest release //libgnustl_shared.so

### ISSUE THREAD

**Issue by mleq0xd** [ChristopherHX/mcpelauncher-manifest#78] opened 2020-04-21 21:48 UTC
IM ON MAC IF THAT HLPS // MOJAVE

22:46:45 Info  [Launcher] Version: client 7c17ac3 / manifest 05861bf
22:46:45 Info  [Launcher] CPU: GenuineIntel Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz
22:46:45 Info  [Launcher] CPU supports SSSE3: YES
22:46:45 Trace [Launcher] Loading hybris libraries
22:46:45 Trace [HybrisUtils] Loaded OS library /Applications/Minecraft Bedrock Launcher.app/Contents/Resources/mcpelauncher/libs/native/libfmod.dylib
22:46:45 Trace [HybrisUtils] Loaded OS library libm.dylib
22:46:45 Error [HybrisUtils] Failed to load OS library libz.so.1
22:46:45 Info  [Launcher] Creating window
22:46:45 Trace [Launcher] Loading gamepad mappings: /Applications/Minecraft Bedrock Launcher.app/Contents/Resources/mcpelauncher/gamecontrollerdb.txt
22:46:48 Trace [Launcher] Loading Minecraft library
linkerlibc++abi.dylib: terminating with uncaught exception of type std::runtime_error: Failed to load Minecraft: Cannot load library: link_image[1969]:     0 could not load needed library 'libgnustl_shared.so' for 'libminecraftpe.so' (load_library[1119]: Library 'libgnustl_shared.so' not found)
Process exited with unexpected exit code: 9

**Comment by ChristopherHX** [comment] 2020-04-21 22:33
Duplicate of https://github.com/ChristopherHX/mcpelauncher-manifest/issues/72#issuecomment-614833126

Note you don't need to compile from source, your dmg is fine

**Comment by mleq0xd** [comment] 2020-04-22 00:08
> Duplicate of [#72 (comment)](https://github.com/ChristopherHX/mcpelauncher-manifest/issues/72#issuecomment-614833126)
> 
> Note you don't need to compile from source, your dmg is fine

I didnt compile I used the dmg and followed instructions that you given to the last guy with the same problem as me. However its still not working, any ideas ??

**Comment by ChristopherHX** [comment] 2020-04-22 13:55
My statement from minecraft-linux discord server
```I believe all you errors are result of a corrupted download of Minecraft 1.14.60.5+ (happen with an outdated Launcher / mcpelauncher-extract)
1. Make shure you have installed the appimage or DMG (of my fork see pinned messages) (or install my mcpelauncher-ui-qt .deb / pkg.*)
2. Open launcher settings
3. select 1.14.60.5
4. press delete or remove
5. close settings
6. Download and run the Minecraft 1.14.60.5 via the updated launcher
```
**You would be the first one, who would keep getting your posted error after following the steps carefully**
If it is another error feel free to post it here.

**Closed** 2020-05-17 14:06 UTC
Labels: duplicate
