### ISSUE TITLE
1.16.20 don't start

### ISSUE THREAD

**Issue by AtlanticDany** [ChristopherHX/mcpelauncher-manifest#131] opened 2020-08-13 06:51 UTC
08:50:35 Info  [Launcher] Version: client 4432ade / manifest 3cbce17
08:50:35 Info  [Launcher] CPU: GenuineIntel Intel(R) Core(TM)2 Duo CPU     T8100  @ 2.10GHz
08:50:35 Info  [Launcher] CPU supports SSSE3: YES
08:50:35 Trace [Launcher] Loading hybris libraries
08:50:35 Trace [HybrisUtils] Loaded OS library /tmp/.mount_MC.AppT9Ez7v/usr/share/mcpelauncher/libs/native/libfmod.so.9.16
08:50:35 Trace [HybrisUtils] Loaded OS library libm.so.6
08:50:35 Trace [HybrisUtils] Loaded OS library libz.so.1
08:50:35 Info  [Launcher] Creating window
08:50:35 Trace [Launcher] Loading gamepad mappings: /tmp/.mount_MC.AppT9Ez7v/usr/share/mcpelauncher/gamecontrollerdb.txt
_eglutReadPNG: fopen failed
08:50:35 Trace [Launcher] Loading Minecraft library
linker
Unsupported or corrupted Minecraft install detected, please delete the Version in settings and redownload

**Comment by chinoto** [comment] 2020-08-13 14:45
Duplicate of #129

**Closed** 2020-08-18 17:49 UTC
